name: Profile Metrics

on:
  schedule:
    - cron: "0 0 * * 1" # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Trophies
        uses: ryo-ma/github-profile-trophy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate Stats SVG
        run: |
          mkdir -p dist
          node scripts/stats.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add dist/

          git commit -m "chore: update profile metrics" || exit 0
          git push
